INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (200, 'Otwarty swiat');
INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (201, 'Survival');
INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (202, 'Strzelaniny');
INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (204, 'Horror');
INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (205, 'Symulator');
INSERT INTO SKLEP.KATEGORIE (KATE_ID, KATE_NAZWA) VALUES (206, 'PlatformÃ³wka');